### ISSUE TITLE
Deprecation warning from npm install

### ISSUE THREAD

**Issue by judyyang40** [consenlabs/tokenlon-sdk#5]
Hi,
I'm getting the following warning: 
deprecated bignumber.js@6.0.0: Custom ALPHABET bug fixed in v7.0.2
This might not be a breaking bug, but maybe consider upgrading the bignumber dependency?

**Comment by w7788129** [comment]
Go

**Comment by Xaber20110202** [comment]
Hi, thanks for your advice!
We only import `Bignumber` from `@0xproject/utils`, and we removed this `bignumber.js@6.0.0` dependence at 0.3.1.
